### ISSUE TITLE
Lib does not work on Ubuntu LTS 16.04

### ISSUE THREAD

**Issue by Strikerrr** [discordjs/RPC#24]
Trying to use crawl's vscode extension and it doesn't work. Crawl suggested it was because of the lib, any advice?

**Comment by RONTheCookie** [comment]
I'm using maxerbox's vscode-discord extenstion, and what I did is go to this path `/home/YOUR USERNAME/.vscode/extensions/maxerbox.vscode-discord-1.0.2/node_modules/discord-rpc/src/transports`
then I opened IPC.js - went to the getIPCPath function (line 102 for me) and made it always return "/run/user/1000/discord-ipc-0":
This is what it looks like:
![image](https://user-images.githubusercontent.com/25263210/37967182-4a588c32-31d3-11e8-8b80-3c3678c8c64d.png)

And it has been working perfectly for me since I did that.

**Comment by Strikerrr** [comment]
@RONTheCookie thanks my dude, I'll try this solution when I can thanks.

**Comment by RONTheCookie** [comment]
:ok_hand:

**Comment by Strikerrr** [comment]
Won't be closing this until I know it works also, but thanks :)

**Comment by RONTheCookie** [comment]
maybe you should close this issue already

**Comment by Strikerrr** [comment]
Works

**Comment by RONTheCookie** [comment]
Great 👌
