### ISSUE TITLE
My RPC issues

### ISSUE THREAD

**Issue by JattiDev** [discordjs/RPC#28]
First one is that **nobody** wants to even help with it on your official discord.js server
Second is **very** bad docs like in example is:
```
// Log in to RPC with client id and access token
client.login(clientID, { accessToken, scopes });
```
and then in docs is:
```
  /**
   * @typedef {RPCLoginOptions}
   * @param {string} [clientSecret] Client secret
   * @param {string} [accessToken] Access token
   * @param {string} [rpcToken] RPC token
   * @param {string} [tokenEndpoint] Token endpoint
   */
```
where in this is something about scopes?

And on webpage https://discord.js.org/#/docs/rpc/master/class/RPCClient is just that xD

Third one is about connection, websocket doesn't work for me for unknown reason but when I asked on official server, of course nobody wanted to help, even devs, there were just messages from people who doesn't like RPC idea at all, so very good support, anyways ipc option doesn't work at all, I tried to use it but it just throws errors, something with constructor, idk really why.

Another issue is that you don't merge PRs there are two of them right now, and one is waiting 10 days. For me, it all is silly cuz like RPC is part of discord, and discord.js too. So why do you treat it like that?...

**Comment by devsnek** [comment]
> where in this is something about scopes?

welcome to open source. if you find a problem you're welcome to open a pr, but complaining about it isn't very nice. please be more considerate of maintainers of open source projects.

> Third one is about connection, websocket doesn't work for me for unknown reason

using the websocket requires being whitelisted by discord. use ipc.

> Another issue is that you don't merge PRs there are two of them right now, and one is waiting 10 days. 

i'm not available 24/7 to be managing this library, in fact the only reason i found time to go through this right now is because i'm in bed with a fever. please be more considerate of maintainers of open source projects in the future.
