### ISSUE TITLE
Author thinks breaking the package on purpose is not an issue

### ISSUE THREAD

**Issue by Saren-Arterius** [discordjs/RPC#34]
> beta versions of rpc are purposely pinned to discord.js master branch.

And that's why things will break eventually. 

Does this mean "my beta version package is not supposed to work, so even if it works for you now, I am making sure that it will not work eventually"?

This is a real issue, if the author thinks none of the reported issues are meaningful to you, or you think you are exhausted to treat other devs properly, you are welcome to close the whole issue board.

**Comment by kyranet** [comment]
I'll suggest you something, `cd /node_modules/discord-rpc && npm i && npm i discordjs/discord.js#your-desired-commit-hash`.

Problem solved, and please don't open the same issue multiple times.

**Comment by james58899** [comment]
But this just workaround, I think this issue should be fix

**Comment by kyranet** [comment]
To be honest, what I do in some repositories is make discord.js a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/), so people install their desired version/commit hash, although the support becomes more tricky because it's very hard to enforce support in a library that is quickly changing.

Nonetheless, when `discord-rpc` becomes stable, it'll most likely use a stable version of discord.js, being either v12.0.0 (whenever it releases as stable) or locked to a commit. This library is currently beta, so you shouldn't expect full stability.

**Comment by devsnek** [comment]
I actually pin them to master because rpc will become stable with v12 and pinning to a hash will backtrack compat. I appreciate that you think I don't care but in actuality I'm just being pragmatic.
