### ISSUE TITLE
o.createConnection is not a function

### ISSUE THREAD

**Issue by nari3310** [discordjs/RPC#99]
Using `vue-cli` and `discord-rpc`, I have this error in the catch of my `rpc.login()`.
Example code :
```js
const rpc = new Client({ transport: 'ipc' })
rpc.login({ clientId: this.rpc.appId })
      .then(() => {
         console.log("Success")
       })
       .catch((err) => {
          console.log(err)
       });
```

**Comment by ScottyFillups** [comment]
You're likely trying to use this library in a web application. This library offers two transport types: `ipc` and `websocket`. Your application must be whitelisted by Discord to use `websocket`. Anyone can use `ipc` though: that's what you appear to be using.

IPC stands for "inter-process communiation": rather than communicating across a network using HTTP, you're communicating with the Discord client using a shared block of memory. Unfortunately, web applications cannot communicate via IPC (for security reasons).

The reason you're getting `o.createConnection is not a function` is because this library is attempting to use Node.js's `net` library, which isn't available for web applications. Here's the function the library is trying to call: https://nodejs.org/api/net.html#net_net_createconnection_path_connectlistener

BTW I don't really know what I'm doing as well so I might be partially wrong, sorry :P

**Comment by FBuckette** [comment]
Don't worry, and thanks for the answer. But now, if I want to use my app with `vue-cli`, I must use `websocket` and be whitelisted by Discord ?

**Comment by ScottyFillups** [comment]
Yeah; I'm not too familiar with the process
